"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config

# Try importing dj_database_url, fall back if not installed locally yet
try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-lxvl&l-xrju8r=ie^ux35sj!$%94m+ko^252os@!#f%&wg@a$i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Automatically detect and allow all possible network IPs
import socket

def get_local_ip():
    """Get the local IP address of the machine"""
    try:
        # Connect to a remote address to get local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(1.0)
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
        s.close()
        return local_ip
    except Exception:
        return None

# Load ALLOWED_HOSTS from environment in production
ALLOWED_HOSTS_ENV = config('ALLOWED_HOSTS', default='')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Get current local IP
    current_ip = get_local_ip()

    # Comprehensive ALLOWED_HOSTS that covers all scenarios
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '0.0.0.0',
        '::1',  # IPv6 localhost
    ]

    # Add current network IP if detected
    if current_ip:
        ALLOWED_HOSTS.append(current_ip)
        # Also add common network variations
        ip_parts = current_ip.split('.')
        if len(ip_parts) == 4:
            network_prefix = f"{ip_parts[0]}.{ip_parts[1]}.{ip_parts[2]}"
            # Add common network IPs
            for i in range(1, 255):
                ALLOWED_HOSTS.append(f"{network_prefix}.{i}")

    # Add previously known IPs
    ALLOWED_HOSTS.extend([
        '10.97.171.119',  # Your previous IP
        '10.198.33.119',  # Your old IP
        '10.231.22.119',  # Your previous IP
        '10.214.9.119',   # Your current IP (Feb 2026)
    ])

    # Remove duplicates and sort
    ALLOWED_HOSTS = sorted(list(set(ALLOWED_HOSTS)))

# Automatically detect and append Render hostname if deployed on Render
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    ALLOWED_HOSTS = sorted(list(set(ALLOWED_HOSTS)))

# CSRF Trusted Origins for Django Admin panel security
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

print(f"[Settings] Django ALLOWED_HOSTS configured for: {ALLOWED_HOSTS}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',  # Must come before django.contrib.staticfiles
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
    'cloudinary',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add WhiteNoise for production static file serving (only if installed)
try:
    import whitenoise  # noqa: F401
    MIDDLEWARE.insert(2, 'whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Production: Set DATABASE_URL env var (e.g. postgresql://user:pass@host:5432/dbname)
# Development: Falls back to SQLite automatically

DATABASE_URL = config('DATABASE_URL', default='postgresql://postgres:postgres@127.0.0.1:5432/rozzi')

# We only allow SQLite fallback in local development (DEBUG=True) when using a local database host
is_local_db = '127.0.0.1' in DATABASE_URL or 'localhost' in DATABASE_URL
allow_fallback = DEBUG and is_local_db

use_sqlite_fallback = False
if DATABASE_URL and dj_database_url:
    try:
        import psycopg2
        # Try to connect with a short timeout to see if PostgreSQL is available
        conn = psycopg2.connect(DATABASE_URL, connect_timeout=2)
        conn.close()
        
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
                engine='django.db.backends.postgresql',
            )
        }
        print(f"[Settings] Database: PostgreSQL (via DATABASE_URL)")
    except Exception as e:
        if allow_fallback:
            print(f"[Settings] Local PostgreSQL connection check failed: {e}. Falling back to SQLite.")
            use_sqlite_fallback = True
        else:
            print(f"[Settings] CRITICAL: PostgreSQL connection failed: {e}. Strict mode (no SQLite fallback in production).")
            raise e
else:
    use_sqlite_fallback = True

if use_sqlite_fallback or not dj_database_url:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print(f"[Settings] Database: SQLite (local development fallback)")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files configuration - Cloudinary handles media storage
MEDIA_URL = 'https://res.cloudinary.com/dnr1qtmyf/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Fallback for development

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}


# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://localhost:8082",
    "http://127.0.0.1:8082",
    "http://10.184.206.119:8081",
    "http://10.184.206.119:8082",
    "http://10.62.138.119:8081",
    "http://10.62.138.119:8082",
    "http://10.62.138.119:3000",
    "http://10.231.22.119:8081",  # Current IP for React Native
    "http://10.231.22.119:8082",  # Current IP for React Native
    "http://10.231.22.119:3000",  # Current IP for React Native
    "http://10.235.243.119:8081", # Newest IP (Mar 2026)
    "http://10.235.243.119:8082",
    "http://10.235.243.119:3000",
]

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # CORS for production
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        # Add your production domain here
        "https://your-domain.com",
    ]


# Cloudinary configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dnr1qtmyf',
    'API_KEY': '571633454864952',
    'API_SECRET': 'rJ4MBW5XahGzXshlhvaYTSRJVEw',
    'STATIC_TAG': 'static',
    'MEDIA_TAG': 'media',
    'INVALID_VIDEO_ERROR_MESSAGE': 'Please upload a valid video file.',
    'STATIC_IMAGES_EXTENSIONS': ['jpg', 'jpe', 'jpeg', 'jpc', 'jp2', 'j2k', 'wdp', 'jxr', 'hdp', 'png', 'gif', 'webp', 'bmp', 'tif', 'tiff', 'ico'],
    'MAGIC_FILE_PATH': 'magic',
    'STATIC_IMAGES_TRANSFORMATIONS': {
        'format': 'auto',
        'fetch_format': 'auto',
    }
}

# Cloudinary Admin API configuration (for cleanup operations)
CLOUDINARY_CONFIG = {
    'cloud_name': 'dnr1qtmyf',
    'api_key': '571633454864952',
    'api_secret': 'rJ4MBW5XahGzXshlhvaYTSRJVEw',
    'secure': True
}

# File storage configuration
if DEBUG:
    # Development: Use Cloudinary for media, local for static
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # Production: Use Cloudinary for both media and static
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

# Razorpay Configuration
from decouple import config
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='rzp_test_placeholder_key')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='placeholder_secret')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='placeholder_webhook_secret')

# Google Authentication Client IDs (Audience verification)
GOOGLE_CLIENT_IDS = [
    config('GOOGLE_WEB_CLIENT_ID', default='370990896857-t1gnvm3c4n2apfu4ugpr9ccpoae580qd.apps.googleusercontent.com'),
    config('GOOGLE_ANDROID_CLIENT_ID', default='370990896857-1mlsie4r8s30jc8753u5tbdcath60pkv.apps.googleusercontent.com'),
    config('GOOGLE_IOS_CLIENT_ID', default=''),
]
# Filter out empty values (e.g. if GOOGLE_IOS_CLIENT_ID is not configured)
GOOGLE_CLIENT_IDS = [cid for cid in GOOGLE_CLIENT_IDS if cid]

# Cache Configuration
# Production: Set REDIS_URL env var (e.g. redis://default:password@host:6379)
# Development: Falls back to LocMemCache (in-memory, no setup needed)
REDIS_URL = config('REDIS_URL', default=None)

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,  # 5 minutes default TTL
            'OPTIONS': {
                'db': '0',
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
                'retry_on_timeout': True,
            },
            'KEY_PREFIX': 'rozzi',
        }
    }

    # Use Redis for sessions too (faster, survives server restarts)
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'

    print(f"[Settings] Cache: Redis")
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': 300,
            'KEY_PREFIX': 'rozzi',
        }
    }
    print(f"[Settings] Cache: LocMemCache (local development)")