# Generated by Django 5.1.2 on 2025-08-12 01:14

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, help_text='Cloudinary photo URL', max_length=500, null=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('post_type', models.CharField(choices=[('hire', 'Hire'), ('looking', 'Looking')], default='hire', max_length=20)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('One-time', 'One-time'), ('Contract', 'Contract')], default='Full-time', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Delivery', 'Delivery'), ('Fitness', 'Fitness'), ('Content', 'Content'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Finance', 'Finance'), ('Other', 'Other')], default='Technology', max_length=100, null=True)),
                ('sector', models.CharField(choices=[('Local', 'Local'), ('Professional', 'Professional')], default='Professional', max_length=50)),
                ('experience_level', models.CharField(choices=[('not mentioned', 'Not mentioned'), ('fresher', 'Fresher'), ('0 to 2 years', '0 to 2 years'), ('1 to 3 years', '1 to 3 years'), ('3+ years', '3+ years'), ('5+ years', '5+ years')], default='not mentioned', max_length=50)),
                ('deadline', models.CharField(choices=[('1 day', '1 day'), ('3 days', '3 days'), ('7 days', '7 days'), ('15 days', '15 days'), ('30 days', '30 days')], default='15 days', max_length=50)),
                ('shift_timing', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Not mentioned', 'Not mentioned')], default='Not mentioned', max_length=50)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('pincode', models.CharField(default='', max_length=10)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants_count', models.IntegerField(default=0)),
                ('is_remote', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume_files')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('is_default', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures')),
                ('username_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_username_change', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Optional message from the requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='core.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('custom_field_answers', models.JSONField(blank=True, default=list)),
                ('id_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.idcard')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.resumefile')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
