# Generated by Django 5.1.2 on 2026-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
