# Generated by Django 5.1.2 on 2026-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_google_email_userprofile_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender_preference',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10),
        ),
    ]
