# Generated by Django 5.1.2 on 2026-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_gender_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requires_resume_url',
            field=models.BooleanField(default=False, help_text='If enabled, applicants must provide a Google Drive resume URL'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_url',
            field=models.URLField(blank=True, help_text='Resume URL submitted with this application', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='file_name',
            field=models.CharField(help_text='Display name for the resume', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='file_size',
            field=models.IntegerField(default=0, help_text='Deprecated - kept for backward compatibility'),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='file_url',
            field=models.URLField(help_text='Google Drive resume URL', max_length=500),
        ),
    ]
