# Generated by Django 6.0.5 on 2026-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resume_url_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_application_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('seeker_29', 'Seeker 29'), ('recruiter_99', 'Recruiter 99')], default='free', max_length=20),
        ),
    ]
