# Generated by Django 6.0.5 on 2026-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('One-time', 'One-time'), ('Contract', 'Contract')], db_index=True, default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='pincode',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_type',
            field=models.CharField(choices=[('hire', 'Hire'), ('looking', 'Looking')], db_index=True, default='hire', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft')], db_index=True, default='Open', max_length=50),
        ),
    ]
